language: ruby
rvm:
  - "2.2.2"
env:
  - DB=postgres
before_script:
  - cp config/database.travis.yml config/database.yml
  - cp config/application.travis.yml config/application.yml
  - cp config/secrets.travis.yml config/secrets.yml
  - bundle exec rake db:create db:migrate --trace
  - chmod +x scripts/saddler.sh
  - scripts/saddler.sh
script:
  - RAILS_ENV=test bundle exec rspec spec
secure: "aogNeHC/oSaGUDarLHvB7U/XaOrsnP01t99tBEMdD83T0+yNa9LxXiZYtLNgHl6iN6D6cRJFCMiFdhS4nDvRFVb1tXCA7gGglgz8zGc6x0sIEpJfEFVoND9vbmzQG5sbM4Pr/0G2F97qt6F8JiC/rjDDvGvbKItPK5M3MadQX4hlCYUxpXE1CZ+2bhPaw9uQPrvsO/0iT58GJaGuh/q+AC+Q3SPfch4Qg77ABlZ4wIyjmyx7ghCXeJMJpvrtMGqqQ+7HJE7D0yyOnIiJzAvu/gBFGz+FCBSK3toAmyizB2HIcRWZCw3oTCdCQ/1u3uGptQByymmSIhmvskzCLl66DpnO/CtqwxDpd3lFV+skuQGM4TYDy+B/E+vAVeKhTGTAvTa7/crevoGFXR7olerqFmWxXXtYLfJYeA3q7kxyE6nZqTlfMhjGNpqUAn1BvRhvDyJ9uSoFcekq7sOaWyEVKLV/e3SLJk8PCdgphp7I0rG7JdSMDIu22aHkcOpWmYUniKpLXvH/WfX8UjI+q4NypaNoAXSEgdK+nD8A53DBDROroxoouS/eTm3vAJ/AURM3/LOy5kv+Ovmbw+LLcH8gF/ciVuMtELd+d43P5fYCNoZPs/ijm7JpFohE4wFj/gwLBfnfeXQ7Ns2QFRKtdTdkkfJ/ctI6s06GNEMCLbN1UmM="
