default: &default
  adapter: postgresql
  encoding: utf8
  charset: utf8
  pool: 5
  username: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432

development:
  <<: *default
  database: blackhulk_development

test:
  <<: *default
  database: blackhulk_test
