# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 484bf18748e7a1798a6dc908ab766581da6b320c4bb99778d4d4a8c1988989fe0a68382c33fae02ed137ec536afea5b8e4649a019ac12453346a918b8f53b4ba

test:
  secret_key_base: 3109ae49f7aa6868d279741011c1dc635f54c3bb0fe64d93deaa18f1c81ff14032333abbd02d3700614e07285b4a6ed8d5c72fdc3b04d79faa1e566f0714d207

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
